# Generated by Django 3.2.2 on 2021-05-10 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emailv1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailv1',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
