# Generated by Django 3.2.2 on 2021-05-10 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailv1', '0002_emailv1_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailv1',
            old_name='email_adress',
            new_name='email_address',
        ),
    ]
