version: '3'

services:
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'backend-residuall'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: '1234'
       MYSQL_ROOT_PASSWORD: '1234'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/my_app_dir
    ports:
      - "8080:8080"
    depends_on:
      - db