# Generated by Django 3.2.2 on 2021-05-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emailv3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=20)),
                ('valid_syntax', models.BooleanField(default=False)),
                ('disposable', models.BooleanField(default=False)),
                ('webmail', models.BooleanField(default=False)),
                ('deliverable', models.BooleanField(default=False)),
                ('catch_all', models.BooleanField(default=False)),
                ('gibberish', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
